<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-SQBD1KF4" failures="1" tests="4" name="Test(failed)" time="32.557" errors="0" timestamp="2023-01-06T12:00:45 IST">
  <testcase classname="TestCases.InventoryPageTest" name="addProductTest" time="4.397">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at TestCases.InventoryPageTest.addProductTest(InventoryPageTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- addProductTest -->
  <testcase classname="TestCases.InventoryPageTest" name="verifyProductsLogoTest" time="2.061"/>
  <testcase classname="TestCases.LoginPageTest" name="verifyLoginLogoTest" time="0.037"/>
  <testcase classname="TestCases.LoginPageTest" name="verifyTitleTest" time="0.009"/>
  <testcase classname="TestCases.LoginPageTest" name="verifyBotLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyBotLogoTest -->
  <testcase classname="TestCases.LoginPageTest" name="loginToAppTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginToAppTest -->
  <testcase classname="TestCases.LoginPageTest" name="verifyLoginPageURLTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginPageURLTest -->
</testsuite> <!-- Test(failed) -->
